all:
 vars:
   ansible_user: admin
   ansible_ssh_private_key_file: ansible/inventories/id_rsa
   ansible_python_interpreter: /usr/bin/python3
 children:
   prod:
     hosts: ahmedzaidmacyl99.takima.cloud
