name: CI devops 2025
on:
  # Event : Running jobs on push and pull request on specified branches
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # checkout to the source code
      - uses: actions/checkout@v4

      # Configure JDK for this actions/setup-java@4 it's required to define the distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      # build and test app
      - name: Build and test with Maven
        run: |
          cd simple-api
          mvn clean verify

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    env:
      DOCKER_IMAGE_NAME: "tp-devops-simple-api"
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./simple-api
          # Note: tags has to be all lower-case
          tags: ${{env.DOCKER_HUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}
          push: ${{ github.ref == 'refs/heads/main' }}

      # - name: Build image and push database
      #     # DO the same for database

      # - name: Build image and push httpd
      #     # DO the same for httpd
