name: CI devops 2025
on:
  # Event : Running jobs on push and pull request on specified branches
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: 
      - main
      - develop

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     # checkout to the source code
      - uses: actions/checkout@v4

     # Configure JDK for this actions/setup-java@4 it's required to define the distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'

     # build and test app
      - name: Build and test with Maven
        run:  mvn clean verify
