name: Push docker images
on:
  # Event : Running jobs on push and pull request on specified branches
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Test Backend"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    env:
      API_IMAGE_NAME: "tp-devops-simple-api"
      DATABASE_IMAGE_NAME: "tp-devops-simple-database"
      HTTP_SERVER_IMAGE_NAME: "tp-devops-simple-http-server"
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./simple-api
          # Note: tags has to be all lower-case
          tags: ${{env.DOCKER_HUB_USERNAME}}/${{env.API_IMAGE_NAME}}:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push database image
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database # Path to the directory containing the Dockerfile for the database
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DATABASE_IMAGE_NAME }}:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push HTTP server image
      - name: Build image and push http-server
        uses: docker/build-push-action@v6
        with:
          context: ./http-server # Path to the directory containing the Dockerfile for the HTTP server
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.HTTP_SERVER_IMAGE_NAME }}:latest
          push: ${{ github.ref == 'refs/heads/main' }}
